# NumPy

```
pip install numpy
```

In [1]:
# !pip install numpy

In [1]:
import numpy as np

In [6]:
x = np.random.randn(13,1) # range(10)
x

array([[ 1.58245146],
       [ 1.55597356],
       [-0.36585944],
       [ 1.84372551],
       [-0.01471649],
       [-0.5590875 ],
       [-1.18490054],
       [ 0.31929521],
       [ 0.60847834],
       [-0.62135238],
       [-0.84537332],
       [-0.94900318],
       [-0.40814332]])

In [9]:
np.maximum(x,0).shape

(13, 1)

In [4]:
x.dot(np.ones_like(x).T)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [4]:
x.shape

(10,)

multi dimensional array

In [5]:
x = np.array([[1,3,4,5],range(4)])
x

array([[1, 3, 4, 5],
       [0, 1, 2, 3]])

In [6]:
x.shape

(2, 4)

In [8]:
x[0,1]==3,x[0,1]

(True, 3)

In [10]:
x[1,2]==2,x[1,2]

(True, 2)

In [11]:
x[1,-1] # 1st row and -1 means last column

3

In [12]:
x[1,-2]

2

In [15]:
x[:,:2],x[:,:2].shape

(array([[1, 3],
        [0, 1]]),
 (2, 2))

In [18]:
x[:,::2] # x[:,startcol_index:endcol_index:step]

array([[1, 4],
       [0, 2]])

In [19]:
a = np.arange(25).reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
a.shape

(5, 5)

In [25]:
# 3D 

x = np.arange(27).reshape((2,3,3,3))
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [26]:
x[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [29]:
x[-1,-1]

array([24, 25, 26])

In [30]:
x[-1,:,2]

array([20, 23, 26])