Matrix: 
- diagonal matrix | `np.diag()`
- identity matrix | `np.eye()` | `np.identity()`
- transpose of a matrix and its properties 
- Upper triangular and lower triangular matrix | `np.tril` | `np.triu`
- scalar matrix



In [1]:
import numpy as np

In [2]:
x = np.arange(20).reshape((4,5))
x,x.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 (4, 5))

In [3]:
np.trace(x) # sum of diagonal elements

36

In [4]:
y = np.arange(16).reshape((4,4))
y,y.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 (4, 4))

In [7]:
np.diag(y).sum()

30

In [6]:
np.trace(y)

30

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [11]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
y.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [17]:
np.diag(y), np.diag(y.T)

(array([ 0,  5, 10, 15]), array([ 0,  5, 10, 15]))

In [13]:
y.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [14]:
y.T.T == y

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [15]:
y.T ==y

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [18]:
(5*y).T == 5*(y.T)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
z = -1*np.arange(16).reshape((4,4))
z

array([[  0,  -1,  -2,  -3],
       [ -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11],
       [-12, -13, -14, -15]])

In [21]:
(y+z).T == z.T + y.T 


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
x,x.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 (4, 5))

In [26]:
np.matmul(y,x).T == np.matmul(x.T,y.T)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
y


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
np.tril(y)

array([[ 0,  0,  0,  0],
       [ 4,  5,  0,  0],
       [ 8,  9, 10,  0],
       [12, 13, 14, 15]])

In [29]:
np.triu(y)

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 0,  0, 10, 11],
       [ 0,  0,  0, 15]])

In [30]:
np.tril(y)+np.triu(y) == y

array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [31]:
3*np.eye(3)

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

vstack, hstack, column stack, row stack 

In [33]:
x,y , x.shape , y.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 (4, 5),
 (4, 4))

In [34]:
np.column_stack((x,y))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3],
       [ 5,  6,  7,  8,  9,  4,  5,  6,  7],
       [10, 11, 12, 13, 14,  8,  9, 10, 11],
       [15, 16, 17, 18, 19, 12, 13, 14, 15]])

In [36]:
np.hstack((x,y)),np.hstack((x,y)).shape # axis = 1 

(array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3],
        [ 5,  6,  7,  8,  9,  4,  5,  6,  7],
        [10, 11, 12, 13, 14,  8,  9, 10, 11],
        [15, 16, 17, 18, 19, 12, 13, 14, 15]]),
 (4, 9))

In [39]:
np.concatenate((x[:,:-1],y),axis=0)

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
x[:,:-1].shape

(4, 4)

In [43]:
np.vstack((x[:,:-1],y)) == np.row_stack((x[:,:-1],y))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])