In [1]:
import torch 

create a multi dimensional array

In [2]:
a = torch.tensor([range(4),range(4,8)])
a,a.shape,a.dtype

(tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
 torch.Size([2, 4]),
 torch.int64)

array indexing

In [3]:
print('element at row 0 col 0\t',a[0,0])
print('element at row 0 col 3\t',a[0,3])
print('element at row 1 col 2\t',a[1,2])

element at row 0 col 0	 tensor(0)
element at row 0 col 3	 tensor(3)
element at row 1 col 2	 tensor(6)


stroage element size

In [4]:
a.element_size()

8

1D array slicing

In [5]:
x = torch.tensor(range(10))
x,x[:4],x[6:],x[4:6]

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0, 1, 2, 3]),
 tensor([6, 7, 8, 9]),
 tensor([4, 5]))

In [6]:
x[::-1] # can reverse like this cause step size msut be >0

ValueError: step must be greater than zero

In [8]:
torch.flip(x,dims=(0,)) # dims must be a tuple

tensor([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])